version: '3.4'

services:
  contato-api-prova:
    image: contato-api-prova
    build:
      context: .
      dockerfile: bdiApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
    ports:
      - "44331:80"
    links:
      - db_api_contato_prova_sqlserver
    depends_on:
      - db_api_contato_prova_sqlserver
    networks:
      - contato-network

  db_api_contato_prova_sqlserver:
    image: db_api_contato_prova_sqlserver  
    build:
     context: .
     dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SA_PASSWORD: "contato@pi10"
      ACCEPT_EULA: "Y"
    ports:
      - "1402:1433"
    networks:
      - contato-network

networks: 
    contato-network:
        driver: bridge