version: '3.4'

services:
  contatoapi:
    image: contatoapi-teste
    build:
      context: .
      dockerfile: bdiApi/Dockerfile
    environment:
      TZ: America/Sao_Paulo 
    ports:
      - "4433:80"
    links:
      - db_api_contato_sqlserver
    depends_on:
      - db_api_contato_sqlserver
    networks:
      - marvel-network

  db_api_contato_sqlserver:
    image: db_api_contato_sqlserver  
    build:
     context: .
     dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      SA_PASSWORD: "contato@pi10"
      ACCEPT_EULA: "Y"
    ports:
      - "1401:1433"
    networks:
      - marvel-network

networks: 
    marvel-network:
        driver: bridge